/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lb_imagesigner_JNIUtil_JNIUtils */

#ifndef _Included_com_lb_imagesigner_JNIUtil_JNIUtils
#define _Included_com_lb_imagesigner_JNIUtil_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lb_imagesigner_JNIUtil_JNIUtils
 * Method:    sayHelloFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lb_imagesigner_JNIUtil_JNIUtils_sayHelloFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_lb_imagesigner_JNIUtil_JNIUtils
 * Method:    imageEncrypt
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_lb_imagesigner_JNIUtil_JNIUtils_imageEncrypt
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_lb_imagesigner_JNIUtil_JNIUtils
 * Method:    signImage
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;IILandroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_lb_imagesigner_JNIUtil_JNIUtils_signImage
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_lb_imagesigner_JNIUtil_JNIUtils
 * Method:    displaySourcImage
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_lb_imagesigner_JNIUtil_JNIUtils_displaySourcImage
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
